variable "aws_account_name" {}
variable "monitoring" {}
variable "uid" {}
variable "prefix" {}
variable "project" {}
variable "environment" {}
variable "creator" {}
variable "sumo_accessid" {}
variable "sumo_accesskey" {}
variable "sumo_env" {}
variable "sumo_org" {}
variable "notify" {}
variable "create_network" {}
variable "create_bastion" {}
variable "create_cluster" {}
variable "vpc" {}
variable "cwl_flowlogs" {}
variable "bastion_role" {}
