apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "otel-demo.name" . }}-frontendclicker'
  labels:
    helm.sh/chart: opentelemetry-demo-0.19.10
    app.kubernetes.io/name: '{{ include "otel-demo.name" . }}'
    app.kubernetes.io/instance: '{{ include "otel-demo.name" . }}'
    app.kubernetes.io/component: frontendclicker
    app.kubernetes.io/version: "1.3.1"
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{ include "otel-demo.name" . }}'
      app.kubernetes.io/instance: '{{ include "otel-demo.name" . }}'
      app.kubernetes.io/component: frontendclicker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: '{{ include "otel-demo.name" . }}'
        app.kubernetes.io/instance: '{{ include "otel-demo.name" . }}'
        app.kubernetes.io/component: frontendclicker
    spec:
      containers:
        - name: frontendclicker
          image: '{{ printf "%s:%s" .Values.sumologic.deployments.frontendclicker.image.repository .Values.sumologic.deployments.frontendclicker.image.tag }}'
          imagePullPolicy: IfNotPresent
          ports: []
          env:
            - name: BROWSER
              value: "chrome"
            - name: DELAY
              value: "5"
            - name: SHOP_URL
              value: 'http://{{ include "otel-demo.name" . }}-frontend:8080'
          resources:
            limits:
              memory: 768Mi
