apiVersion: v2
name: sumo-opentelemetry-demo
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: 0.1.2
dependencies:
  - name: sumologic
    version: 3.6.0
    repository: https://sumologic.github.io/sumologic-kubernetes-collection
  - name: opentelemetry-demo
    version: 0.19.10
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
